# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8744a7e3930a4c386f487f4b53d5c90ed61ae83426a1c209efe558fe0250033857c450b4750f23431218c9ee121222c29b73f705c723095362de9c7c9dcc3ee9

test:
  secret_key_base: 1ebb42342586a0f76df585e6601a5a4a002d11423240b6eaf4d10e5655f512fd5365be848c22669020a20a35a2477b3d02d9cebaf0a15b6bec2000e5ae3d0622

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
